CREATE TABLE GENERO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_GENERO_PK PRIMARY KEY (ID)
);

CREATE TABLE ANIME (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    ESTUDIO VARCHAR(40) NOT NULL,
    GENERO INTEGER,
    FECHA_LANZAMIENTO DATE,
    NUM_TEMPORADAS SMALLINT,
    CAPITULOS SMALLINT,
    ESTADO CHAR(4),
    FAVORITO BOOLEAN,
    IMAGEN VARCHAR(30),
    CONSTRAINT ID_ANIME_PK PRIMARY KEY (ID),
    CONSTRAINT GENERO_ANIME_FK FOREIGN KEY (GENERO) REFERENCES GENERO (ID)
);


