CREATE TABLE ESTUDIO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(3),
    NOMBRE VARCHAR(20) NOT NULL,
    FECHA_LANZAMIENTO DATE,
    CONSTRAINT ID_ESTUDIO_PK PRIMARY KEY (ID)
);

CREATE TABLE ANIME (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    GENERO VARCHAR(200) NOT NULL,
    ESTUDIO INTEGER,
    FECHA_LANZAMIENTO DATE,
    NUM_TEMPORADAS INT,
    CAPITULOS INT,
    ESTADO CHAR(4),
    FAVORITO BOOLEAN,
    IMAGEN VARCHAR(30),
    CONSTRAINT ID_ANIME_PK PRIMARY KEY (ID),
    CONSTRAINT ESTUDIO_ANIME_FK FOREIGN KEY (ESTUDIO) REFERENCES ESTUDIO (ID)
);
